name: selasih_launch
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  get: 4.6.5
  lottie: ^2.6.0
  just_audio: ^0.9.34

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bg/
    - assets/logo/
    - assets/lottie/
    - assets/icon/
    - assets/appicon/
    - assets/audio/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: fonts/plusjakartasans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/plusjakartasans/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/plusjakartasans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: fonts/plusjakartasans/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/plusjakartasans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: fonts/plusjakartasans/PlusJakartaSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/plusjakartasans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/plusjakartasans/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/plusjakartasans/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: fonts/plusjakartasans/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/plusjakartasans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/plusjakartasans/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/plusjakartasans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/plusjakartasans/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
